#
# Buildfile
#
# Author:
#     Michael Tindal <urilith@gentoo.org>
#
# Copyright (C) 2005 Michael Tindal and the individuals listed on
# the ChangeLog entries.
#
# Permission is hereby granted, free of charge, to any person obtaining
# a copy of this software and associated documentation files (the
# "Software"), to deal in the Software without restriction, including
# without limitation the rights to use, copy, modify, merge, publish,
# distribute, sublicense, and/or sell copies of the Software, and to
# permit persons to whom the Software is furnished to do so, subject to
# the following conditions:
# 
# The above copyright notice and this permission notice shall be
# included in all copies or substantial portions of the Software.
# 
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND,
# EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF
# MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND
# NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT HOLDERS BE
# LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER IN AN ACTION
# OF CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION
# WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE SOFTWARE.
#

using [ Core
	Core.Clr
	Core.Install
	Languages.CSharp
	Tools.Bundlegen
]

# information about this project

project [ 
	name = nmodule
	version = 0.1.0.0

	compat-code = 0.1

	ref [ 
		Languages.CSharp = 0.0.4.0
		Tools.Jay = 0.0.4.0
		Tools.PkgConfig = 0.0.4.0
		Tools.Bundlegen = 0.0.4.0
		Tools.Monodoc = 0.0.4.0
	]
]

load Buildfile.config inside config/nmodule

subdirs [
	src
]

TODO = TextSource[] 
	with [ install = /config/nmodule/doc_installer ]
README = TextSource[] 
	with [ install = /config/nmodule/doc_installer ]
INSTALL = TextSource[] 
	with [ install = /config/nmodule/doc_installer ]
NEWS = TextSource[] 
	with [ install = /config/nmodule/doc_installer ]
COPYING = TextSource[]
	with [ install = /config/nmodule/doc_installer ]
AUTHORS = TextSource[]
	with [ install = /config/nmodule/doc_installer ]
