#!/bin/bash

mv ChangeLog .ChangeLog.sch

echo "$(date "+%a %b %d, %Y") $SVKCNAME ($SVKEMAIL) $(date "+%z")" > ChangeLog

svk status | sed -e 's@\?.*@@g' -e 's@.*ChangeLog.*@@' -e '/^$/d' >> ChangeLog

echo "" >> ChangeLog

cat .ChangeLog.sch >> ChangeLog

rm -f .ChangeLog.sch


