#
# Buildfile
#
# Author:
#     Michael Tindal <urilith@gentoo.org>
#
# Copyright (C) 2005 Michael Tindal and the individuals listed on
# the ChangeLog entries.
#
# Permission is hereby granted, free of charge, to any person obtaining
# a copy of this software and associated documentation files (the
# "Software"), to deal in the Software without restriction, including
# without limitation the rights to use, copy, modify, merge, publish,
# distribute, sublicense, and/or sell copies of the Software, and to
# permit persons to whom the Software is furnished to do so, subject to
# the following conditions:
# 
# The above copyright notice and this permission notice shall be
# included in all copies or substantial portions of the Software.
# 
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND,
# EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF
# MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND
# NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT HOLDERS BE
# LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER IN AN ACTION
# OF CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION
# WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE SOFTWARE.
#

using [ Core
        Core.Clr
        Core.Install
        Languages.CSharp
]

# Instead of creating mostly-blank Buildfiles
# in these directories, we can implicitly define
# their contents.

inside [ 
	NModule.Core
	NModule.Dependency.Core
	antlr-runtime
	antlr-runtime/antlr
	antlr-runtime/antlr.collections
	antlr-runtime/antlr.collections.impl
	antlr-runtime/antlr.debug
	NModule.Dependency.Parser
	NModule.Core.Module
	NModule.Core.Loader
] [
	using [ Core
		Core.Clr
		Languages.CSharp
		Tools.Bundlegen # for Core
	]
]

NModule.Core.dll = [
	@NModule.Core.dll.sources
	nmodule.snk
] with [ install = /config/nmodule/gac_installer ]

NModule.Dependency.Core.dll = [
	@NModule.Dependency.Core.dll.sources
	NModule.Core.dll
	nmodule.snk
] with [ install = /config/nmodule/gac_installer ]

antlr-runtime.dll = [
	@antlr-runtime.dll.sources
	nmodule.snk
] with [ install = /config/nmodule/gac_installer ]

NModule.Dependency.Parser.dll = [
	@NModule.Dependency.Parser.dll.sources
	NModule.Core.dll
	NModule.Dependency.Core.dll
	antlr-runtime.dll
	nmodule.snk
] with [ install = /config/nmodule/gac_installer ]

NModule.Core.Module.dll = [
	@NModule.Core.Module.dll.sources
	NModule.Core.dll
	NModule.Dependency.Core.dll
	NModule.Dependency.Parser.dll
	nmodule.snk
] with [ install = /config/nmodule/gac_installer ]

NModule.Core.Loader.dll = [
	@NModule.Core.Loader.dll.sources
	NModule.Core.dll
	NModule.Core.Module.dll
	NModule.Dependency.Core.dll
	nmodule.snk
] with [ install = /config/nmodule/gac_installer ]
